"""add_new_tables

Revision ID: 2416d0232833
Revises:
Create Date: 2026-05-31 18:04:17.403256

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2416d0232833"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
