"""fixed models

Revision ID: 6091cbb8e3b7
Revises: 16510cc7e19c
Create Date: 2026-05-27 18:27:20.757886

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6091cbb8e3b7"
down_revision: Union[str, Sequence[str], None] = "16510cc7e19c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("categories") as batch_op:
        batch_op.create_unique_constraint("uq_categories_name", ["name"])

    with op.batch_alter_table("order_items") as batch_op:
        batch_op.add_column(sa.Column("product_name", sa.String(), nullable=True))

    with op.batch_alter_table("orders") as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("phone", sa.String(), nullable=False))

    with op.batch_alter_table("users") as batch_op:
        batch_op.add_column(
            sa.Column("first_name", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(sa.Column("last_name", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("username", sa.String(length=50), nullable=True))
        batch_op.drop_index("ix_users_admin")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_users_admin"), "users", ["admin"], unique=False)
    op.drop_column("users", "username")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_column("orders", "phone")
    op.drop_column("orders", "name")
    op.drop_column("order_items", "product_name")
    op.drop_constraint(None, "categories", type_="unique")
    op.create_table(
        "order_info",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("order_id", sa.INTEGER(), nullable=False),
        sa.Column("username", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), nullable=False),
        sa.Column("surname", sa.VARCHAR(length=50), nullable=False),
        sa.Column("city", sa.VARCHAR(length=50), nullable=False),
        sa.Column("address", sa.VARCHAR(), nullable=False),
        sa.Column("email", sa.VARCHAR(), nullable=False),
        sa.Column("phone", sa.VARCHAR(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_info_order_id"), "order_info", ["order_id"], unique=False
    )
    # ### end Alembic commands ###
