"""refresh order schema

Revision ID: 68a98f0f03e4
Revises: 2416d0232833
Create Date: 2026-06-09 20:26:23.799450

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68a98f0f03e4"
down_revision: Union[str, Sequence[str], None] = "2416d0232833"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("full_name", sa.String(), nullable=True))
    op.add_column("orders", sa.Column("address", sa.String(), nullable=True))
    op.alter_column("orders", "phone", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("orders", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.alter_column("orders", "phone", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("orders", "address")
    op.drop_column("orders", "full_name")
    # ### end Alembic commands ###
